# Generated by Django 5.2.7 on 2025-11-15 20:43

from django.db import migrations, models


def convert_integer_to_json(apps, schema_editor):
    """Convert existing integer choice values to JSON format"""
    PollResponse = apps.get_model('polls', 'PollResponse')
    # For PostgreSQL, we need to manually convert the data
    # This will be done via raw SQL
    from django.db import connection
    with connection.cursor() as cursor:
        # Convert integer values to JSON by casting them
        cursor.execute(
            "UPDATE polls_pollresponse SET choice = to_jsonb(choice::int)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pollresponse',
            name='polls_pollr_poll_id_61d106_idx',
        ),
        migrations.AddField(
            model_name='poll',
            name='question_format',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('speed_ranking', 'Speed Ranking')], default='single_choice', max_length=20),
        ),
        # First, convert the data
        migrations.RunSQL(
            sql="ALTER TABLE polls_pollresponse ALTER COLUMN choice TYPE jsonb USING to_jsonb(choice::int);",
            reverse_sql="ALTER TABLE polls_pollresponse ALTER COLUMN choice TYPE integer USING (choice::text)::integer;",
        ),
        # Then update the Django model
        migrations.AlterField(
            model_name='pollresponse',
            name='choice',
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name='pollresponse',
            index=models.Index(fields=['poll'], name='polls_pollr_poll_id_d1344e_idx'),
        ),
    ]
