# Generated by Django 5.2.7 on 2025-11-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_pollresponse_polls_pollr_poll_id_61d106_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question_format',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('speed_ranking', 'Speed Ranking'), ('team_battle', 'Team Battle')], default='single_choice', max_length=20),
        ),
    ]
