# Generated by Django 5.2.7 on 2025-11-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_question_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='correct_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
