# Generated by Django 5.2.7 on 2025-11-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question_format',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('speed_ranking', 'Speed Ranking'), ('team_battle', 'Team Battle'), ('meta_prediction', 'Meta Prediction')], default='single_choice', max_length=20),
        ),
    ]
