# Generated by Django 5.2.7 on 2025-11-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_exit_tickets_and_kind'),
        ('polls', '0005_alter_poll_question_format'),
    ]

    operations = [
    ]
