# Generated by Django 5.2.7 on 2025-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_merge_20251115_2239'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pollresponse',
            name='polls_pollr_poll_id_d1344e_idx',
        ),
        migrations.RenameIndex(
            model_name='exitticketresponse',
            new_name='polls_exitt_ticket__8cc31c_idx',
            old_name='polls_exitt_ticket_i_idx',
        ),
        migrations.AddField(
            model_name='poll',
            name='countdown_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='countdown_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='pollresponse',
            index=models.Index(fields=['poll', 'choice'], name='polls_pollr_poll_id_61d106_idx'),
        ),
    ]
