# Generated by Django 5.2.8 on 2025-11-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_courses_enrollment_links"),
        ("polls", "0006_merge_20251115_2239"),
    ]

    operations = []
