# Generated by Django 5.2.8 on 2025-11-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0007_merge_20251115_2315"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pollresponse",
            name="polls_pollr_poll_id_d1344e_idx",
        ),
        migrations.RenameIndex(
            model_name="exitticketresponse",
            new_name="polls_exitt_ticket__8cc31c_idx",
            old_name="polls_exitt_ticket_i_idx",
        ),
        migrations.AlterField(
            model_name="exitticket",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="poll",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="pollresponse",
            index=models.Index(
                fields=["poll", "choice"], name="polls_pollr_poll_id_61d106_idx"
            ),
        ),
    ]
