# Generated by Django 5.2.7 on 2025-11-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_pollresponse_polls_pollr_poll_id_d1344e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitticket',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
