# Generated by Copilot on 2025-11-15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_exitticket_active_alter_poll_active'),
        ('polls', '0008_remove_pollresponse_polls_pollr_poll_id_d1344e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='countdown_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='countdown_start_time',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
