# Generated by Django 5.2.7 on 2025-11-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_merge_20251115_2315'),
        ('polls', '0008_alter_exitticket_active_alter_poll_active'),
    ]

    operations = [
    ]
